CREATE DATABASE IF NOT EXISTS java CHARSET utf8mb4;
USE java;

CREATE TABLE IF NOT EXISTS users (
	id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    firstname VARCHAR(50),
    lastname VARCHAR(50),
    email VARCHAR(50) UNIQUE NOT NULL,
    `password` VARCHAR(100)
)ENGINE = InnoDB;